In [36]:
import pandas as pd
import numpy
from sklearn import preprocessing

dataset = numpy.loadtxt("iris.csv", delimiter=",")

# attributes = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
# dataset.columns = attributes

X = dataset[:,0:4]
y = dataset[:,4]

normalized_X = preprocessing.normalize(X)
standardized_X = preprocessing.scale(X)

from sklearn import metrics
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
             precision    recall  f1-score   support

       -1.0       1.00      1.00      1.00        50
        0.0       0.98      0.90      0.94        50
        1.0       0.91      0.98      0.94        50

avg / total       0.96      0.96      0.96       150

[[50  0  0]
 [ 0 45  5]
 [ 0  1 49]]
